version: '3.8'
services:
  app:
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
    container_name: vms-backend
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app